language: android
android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build

作者：追风917
链接：http://www.jianshu.com/p/85d4f6bcc93d
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。